# Generated by Django 5.0.7 on 2024-08-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tester',
        ),
    ]
