# Generated by Django 5.0.7 on 2024-08-01 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_image_imagecontainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('PROCESSED', 'processed'), ('COMPLETED', 'completed'), ('CANCELED', 'canceled')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.furniture')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reseller')),
            ],
            options={
                'db_table': '_transaction',
            },
        ),
    ]
