# Generated by Django 5.0.7 on 2024-08-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='access_rights_id',
            new_name='access_rights',
        ),
        migrations.RenameField(
            model_name='furniture',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='furniture',
            old_name='warehouser_id',
            new_name='warehouser',
        ),
        migrations.RenameField(
            model_name='reseller',
            old_name='access_rights_id',
            new_name='access_rights',
        ),
        migrations.RenameField(
            model_name='warehouser',
            old_name='access_rights_id',
            new_name='access_rights',
        ),
    ]
