# Generated by Django 5.0.7 on 2024-08-05 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_access_rights_id_administrator_access_rights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='quantity',
        ),
    ]
