# Generated by Django 5.0.7 on 2024-08-05 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_transaction_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='furniture',
        ),
    ]
