# Generated by Django 5.0.7 on 2024-08-05 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_transaction_furniture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.furniture')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transaction')),
            ],
            options={
                'db_table': '_transaction_detail',
            },
        ),
    ]
