# Generated by Django 5.0.7 on 2024-08-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_transactiondetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='warehouser',
        ),
        migrations.DeleteModel(
            name='Warehouser',
        ),
    ]
